# Configuration file for PageQR

CssSelector = "img.qrcode"

# Paths to scan for pages to generate QR code images.
Include = ["./static/html", "../../../../Downloads/Video"]

# Paths to exclude from the scan for pages to generate QR code images.
Exclude = ["public/bar", "public/foo"]

Extensions = [".html", ".htm"]